### ISSUE TITLE
Convert yolov5s_6.0 to ncnn format?

### ISSUE THREAD

**Issue by maudzung** [nihui/ncnn-assets#6]
Hi @nihui ,
Thanks for your assets. Could you please guide me on how to convert `yolov5s_6.0` to the `ncnn` format? I have seen the converted output in your repo.
Thank you so much!

**Comment by muhammedakyuzlu** [comment]
Hello @maudzung , Did you find the guide that tells you how to convert yolov5s_6.0 to the ncnn format?
